import type { CalendarTask } from './calendar-page';

export const mockTasks: CalendarTask[] = [
  {
    id: 'task-1',
    title: 'Standup',
    project: 'Office Project',
    projectColor: 'var(--blue)',
    dueDate: '2026-12-01T09:00:00',
    durationMinutes: 30,
    priority: 'low',
    status: 'pending',
  },
  {
    id: 'task-2',
    title: 'User interview',
    project: 'Personal Project',
    projectColor: 'var(--purple)',
    dueDate: '2026-12-02T11:00:00',
    durationMinutes: 60,
    priority: 'medium',
    status: 'pending',
  },
  {
    id: 'task-3',
    title: 'Focus session',
    project: 'Deep Work',
    projectColor: 'var(--accent)',
    dueDate: '2026-12-03T10:00:00',
    durationMinutes: 90,
    priority: 'no_priority',
    status: 'in_progress',
  },
  {
    id: 'task-4',
    title: 'Reading',
    project: 'Study',
    projectColor: 'var(--yellow)',
    dueDate: '2026-12-05T11:00:00',
    durationMinutes: 45,
    priority: 'medium',
    status: 'pending',
  },
  {
    id: 'task-5',
    title: 'Assignment',
    project: 'Study',
    projectColor: 'var(--yellow)',
    dueDate: '2026-12-08T13:00:00',
    durationMinutes: 120,
    priority: 'high',
    status: 'pending',
  },
  {
    id: 'task-6',
    title: 'Gym session',
    project: 'Health',
    projectColor: 'var(--accent)',
    dueDate: '2026-12-09T18:00:00',
    durationMinutes: 60,
    priority: 'low',
    status: 'pending',
  },
  {
    id: 'task-7',
    title: 'Design review',
    project: 'Personal Project',
    projectColor: 'var(--purple)',
    dueDate: '2026-12-10T15:30:00',
    durationMinutes: 45,
    priority: 'medium',
    status: 'pending',
  },
  {
    id: 'task-8',
    title: 'Budget review',
    project: 'Office Project',
    projectColor: 'var(--blue)',
    dueDate: '2026-12-17T11:00:00',
    durationMinutes: 60,
    priority: 'medium',
    status: 'done',
  },
  {
    id: 'task-9',
    title: 'Prepare document',
    project: 'Office Project',
    projectColor: 'var(--blue)',
    dueDate: '2026-12-30T14:30:00',
    durationMinutes: 60,
    priority: 'high',
    status: 'pending',
  },
  {
    id: 'task-10',
    title: 'Focus session',
    project: 'Deep Work',
    projectColor: 'var(--accent)',
    dueDate: '2026-12-30T10:00:00',
    durationMinutes: 90,
    priority: 'no_priority',
    status: 'in_progress',
  },
  {
    id: 'task-11',
    title: 'Reply to emails',
    project: 'Office Project',
    projectColor: 'var(--blue)',
    dueDate: '2026-12-30T16:00:00',
    durationMinutes: 30,
    priority: 'medium',
    status: 'pending',
  },
  {
    id: 'task-12',
    title: 'Plan tomorrow',
    project: 'Personal',
    projectColor: 'var(--purple)',
    dueDate: '2026-12-30T21:00:00',
    durationMinutes: 30,
    priority: 'low',
    status: 'pending',
  },
  {
    id: 'task-13',
    title: 'Year-end review',
    project: 'Office Project',
    projectColor: 'var(--blue)',
    dueDate: '2026-12-31T11:00:00',
    durationMinutes: 90,
    priority: 'medium',
    status: 'pending',
  },
];
