import type { PriorityColumnData } from './priority.types';

export const priorityColumns: PriorityColumnData[] = [
  {
    id: 'high',
    title: 'High Priority',
    description: 'Need attention',
    accent: '#ff5757',
    accentRgb: '255 87 87',
    flagColor: 'text-dashboard-danger',
    tasks: [
      {
        id: '1',
        title: 'Submit project proposal',
        dueDate: 'Overdue',
        overdue: true,
        folder: 'Office Project',
        folderColor: 'bg-dashboard-info',
        priority: 'high',
        completed: false,
      },
      {
        id: '2',
        title: 'Prepare Q2 Report',
        dueDate: 'Today',
        folder: 'Office Project',
        folderColor: 'bg-dashboard-info',
        priority: 'high',
        completed: false,
      },
      { id: '3', title: 'Review pull request #47', dueDate: 'Today', folder: 'Office Project', folderColor: 'bg-dashboard-info', comments: 2, priority: 'high', completed: false },
      { id: '4', title: 'CSIT321 Assignment', dueDate: 'Apr 30', overdue: true, folder: 'Study', folderColor: 'bg-dashboard-warning', priority: 'high', completed: false },
      { id: '5', title: 'Buy groceries', dueDate: 'Tomorrow', folder: 'Personal', folderColor: 'bg-violet-400', priority: 'high', completed: false },
      { id: '6', title: 'Workout session', dueDate: 'Tomorrow', folder: 'Health', folderColor: 'bg-dashboard-accent', priority: 'high', completed: false },
    ],
  },
  {
    id: 'medium',
    title: 'Medium Priority',
    description: 'Plan your time',
    accent: '#f5b900',
    accentRgb: '245 185 0',
    flagColor: 'text-dashboard-warning',
    tasks: [
      { id: '7', title: 'Schedule dentist appt.', dueDate: 'May 1', folder: 'Health', folderColor: 'bg-dashboard-accent', priority: 'medium', completed: false },
      { id: '8', title: 'Market research', dueDate: 'May 3', folder: 'Office Project', folderColor: 'bg-dashboard-info', comments: 1, priority: 'medium', completed: false },
      { id: '9', title: 'Design system updates', dueDate: 'May 4', folder: 'Office Project', folderColor: 'bg-dashboard-info', priority: 'medium', completed: false },
      { id: '10', title: 'Read Chapter 5', dueDate: 'May 5', folder: 'Study', folderColor: 'bg-dashboard-warning', priority: 'medium', completed: false },
      { id: '11', title: 'Plan weekend trip', dueDate: 'May 6', folder: 'Personal', folderColor: 'bg-violet-400', priority: 'medium', completed: false },
      { id: '12', title: 'Clean the room', dueDate: 'May 6', folder: 'Personal', folderColor: 'bg-violet-400', priority: 'medium', completed: false },
      { id: '13', title: 'Update portfolio', dueDate: 'May 7', folder: 'Personal', folderColor: 'bg-violet-400', priority: 'medium', completed: false },
      { id: '14', title: 'Book annual checkup', dueDate: 'May 8', folder: 'Health', folderColor: 'bg-dashboard-accent', priority: 'medium', completed: false },
      { id: '15', title: 'Outline presentation', dueDate: 'May 9', folder: 'Office Project', folderColor: 'bg-dashboard-info', priority: 'medium', completed: false },
    ],
  },
  {
    id: 'low',
    title: 'Low Priority',
    description: 'Do when you can',
    accent: '#4295e8',
    accentRgb: '66 149 232',
    flagColor: 'text-dashboard-info',
    tasks: [
      { id: '16', title: 'Watch design tutorial', dueDate: 'May 10', folder: 'Study', folderColor: 'bg-dashboard-warning', priority: 'low', completed: false },
      { id: '17', title: 'Update LinkedIn profile', dueDate: 'May 11', folder: 'Personal', folderColor: 'bg-violet-400', priority: 'low', completed: false },
      { id: '18', title: 'Organize notes', dueDate: 'May 12', folder: 'Study', folderColor: 'bg-dashboard-warning', priority: 'low', completed: false },
      { id: '19', title: 'Learn TypeScript', dueDate: 'May 15', folder: 'Study', folderColor: 'bg-dashboard-warning', comments: 1, priority: 'low', completed: false },
      { id: '20', title: 'Try a new recipe', dueDate: 'May 16', folder: 'Personal', folderColor: 'bg-violet-400', priority: 'low', completed: false },
      { id: '21', title: 'Backup files', dueDate: 'May 17', folder: 'Personal', folderColor: 'bg-violet-400', priority: 'low', completed: false },
      { id: '22', title: 'Meditation', dueDate: 'May 18', folder: 'Health', folderColor: 'bg-dashboard-accent', priority: 'low', completed: false },
    ],
  },
  {
    id: 'none',
    title: 'No Priority',
    description: 'Unprioritized',
    accent: '#9ca3af',
    accentRgb: '156 163 175',
    flagColor: 'text-gray-400',
    tasks: [
      { id: '23', title: 'Idea: Blog about productivity', folder: 'Personal', folderColor: 'bg-violet-400', priority: 'none', completed: false },
      { id: '24', title: 'Sort out old emails', folder: 'Personal', folderColor: 'bg-violet-400', priority: 'none', completed: false },
      { id: '25', title: 'Practice guitar', folder: 'Health', folderColor: 'bg-dashboard-accent', priority: 'none', completed: false },
    ],
  },
];
